module.exports = {
    auth : require('./auth'),
    changeKpi : require('./change-kpi'),
    changeMyPassword : require('./change-my-password'),
    changePps : require('./change-pps'),
    changeStructure : require('./change-structure'),
    changeUsers : require('./change-users'),
    changeRoles : require('./change-roles'),
    choiceAction : require('./choice-action'),
    closeAccounts : require('./close-accounts'),
    createReport : require('./create-report'),
    downloadFile : require('./download-file'),
    getActionsUsers : require('./get-actions-users'),
    getInfo : require('./get-info'),
    pps : require('./pps'),
    setPeriod : require('./set-period'),
    updateWithExcel : require('./update-with-excel'),
    verify : require('./verify'),
    errors: require('./errors')
};